/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "前端学习笔记",
  "description": "学习记录",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/hero2.jpg",
        "actionText": "前往阅读 →",
        "actionLink": "/read/css-mastery/",
        "features": [
          {
            "title": "读书笔记",
            "details": "阅读前端相关书籍的笔记。"
          },
          {
            "title": "技术学习",
            "details": "学习前端技术时的笔记。"
          },
          {
            "title": "日常问题",
            "details": "工作或学习遇到的问题及解决办法。"
          }
        ],
        "footer": "MIT Licensed"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-ae53fb92",
      "path": "/"
    },
    {
      "title": "第8章 响应式",
      "frontmatter": {},
      "regularPath": "/read/css-mastery/8.%E5%93%8D%E5%BA%94%E5%BC%8F.html",
      "relativePath": "read/css-mastery/8.响应式.md",
      "key": "v-19207c0c",
      "path": "/read/css-mastery/8.%E5%93%8D%E5%BA%94%E5%BC%8F.html",
      "headers": [
        {
          "level": 2,
          "title": "8.4 媒体类型与媒体查询",
          "slug": "_8-4-媒体类型与媒体查询"
        },
        {
          "level": 3,
          "title": "8.5.2 媒体查询在何处",
          "slug": "_8-5-2-媒体查询在何处"
        },
        {
          "level": 2,
          "title": "8.6 几种响应式设计模式",
          "slug": "_8-6-几种响应式设计模式"
        },
        {
          "level": 3,
          "title": "8.6.1 响应式文本列",
          "slug": "_8-6-1-响应式文本列"
        },
        {
          "level": 3,
          "title": "8.6.2 没有媒体查询的flexbox",
          "slug": "_8-6-2-没有媒体查询的flexbox"
        },
        {
          "level": 2,
          "title": "8.7 响应式布局之外",
          "slug": "_8-7-响应式布局之外"
        },
        {
          "level": 3,
          "title": "8.7.1 响应式背景图片",
          "slug": "_8-7-1-响应式背景图片"
        },
        {
          "level": 3,
          "title": "8.7.2 响应式嵌入媒体",
          "slug": "_8-7-2-响应式嵌入媒体"
        },
        {
          "level": 3,
          "title": "8.7.3 响应式排版",
          "slug": "_8-7-3-响应式排版"
        }
      ]
    },
    {
      "title": "第10章 变换、过渡与动画",
      "frontmatter": {},
      "regularPath": "/read/css-mastery/10.%E5%8F%98%E6%8D%A2%E3%80%81%E8%BF%87%E6%B8%A1%E4%B8%8E%E5%8A%A8%E7%94%BB.html",
      "relativePath": "read/css-mastery/10.变换、过渡与动画.md",
      "key": "v-5e00962c",
      "path": "/read/css-mastery/10.%E5%8F%98%E6%8D%A2%E3%80%81%E8%BF%87%E6%B8%A1%E4%B8%8E%E5%8A%A8%E7%94%BB.html",
      "headers": [
        {
          "level": 2,
          "title": "10.1 概述",
          "slug": "_10-1-概述"
        },
        {
          "level": 2,
          "title": "10.2 二位变换",
          "slug": "_10-2-二位变换"
        },
        {
          "level": 3,
          "title": "10.2.1 变换原点",
          "slug": "_10-2-1-变换原点"
        },
        {
          "level": 3,
          "title": "10.2.2 平移",
          "slug": "_10-2-2-平移"
        },
        {
          "level": 3,
          "title": "10.2.3 多重变换",
          "slug": "_10-2-3-多重变换"
        },
        {
          "level": 3,
          "title": "10.2.4 缩放和变形",
          "slug": "_10-2-4-缩放和变形"
        },
        {
          "level": 3,
          "title": "10.2.5 二位矩阵变换",
          "slug": "_10-2-5-二位矩阵变换"
        },
        {
          "level": 3,
          "title": "10.2.6 变换与性能",
          "slug": "_10-2-6-变换与性能"
        },
        {
          "level": 2,
          "title": "10.3 过渡",
          "slug": "_10-3-过渡"
        },
        {
          "level": 3,
          "title": "10.3.1 过渡计时函数",
          "slug": "_10-3-1-过渡计时函数"
        },
        {
          "level": 3,
          "title": "10.3.4 延迟过渡",
          "slug": "_10-3-4-延迟过渡"
        },
        {
          "level": 3,
          "title": "10.3.5 过渡的能否",
          "slug": "_10-3-5-过渡的能否"
        },
        {
          "level": 2,
          "title": "10.4 CSS关键帧动画",
          "slug": "_10-4-css关键帧动画"
        },
        {
          "level": 3,
          "title": "10.4.1 动画与生命的幻象",
          "slug": "_10-4-1-动画与生命的幻象"
        },
        {
          "level": 3,
          "title": "10.4.2 曲线动画",
          "slug": "_10-4-2-曲线动画"
        },
        {
          "level": 2,
          "title": "10.5 三维变换",
          "slug": "_10-5-三维变换"
        },
        {
          "level": 3,
          "title": "10.5.1 透视",
          "slug": "_10-5-1-透视"
        }
      ]
    },
    {
      "title": "第11章 高级特效",
      "frontmatter": {},
      "regularPath": "/read/css-mastery/11.%E9%AB%98%E7%BA%A7%E7%89%B9%E6%95%88.html",
      "relativePath": "read/css-mastery/11.高级特效.md",
      "key": "v-b2d8b9fc",
      "path": "/read/css-mastery/11.%E9%AB%98%E7%BA%A7%E7%89%B9%E6%95%88.html",
      "headers": [
        {
          "level": 2,
          "title": "11.1 CSS Shapes",
          "slug": "_11-1-css-shapes"
        }
      ]
    },
    {
      "title": "第12章 品控与流程",
      "frontmatter": {},
      "regularPath": "/read/css-mastery/12.%E5%93%81%E6%8E%A7%E4%B8%8E%E6%B5%81%E7%A8%8B.html",
      "relativePath": "read/css-mastery/12.品控与流程.md",
      "key": "v-23cb5c22",
      "path": "/read/css-mastery/12.%E5%93%81%E6%8E%A7%E4%B8%8E%E6%B5%81%E7%A8%8B.html",
      "headers": [
        {
          "level": 2,
          "title": "12.1 外部代码质量：调试CSS",
          "slug": "_12-1-外部代码质量-调试css"
        },
        {
          "level": 4,
          "title": "12.1.1 浏览器如何解析CSS",
          "slug": "_12-1-1-浏览器如何解析css"
        },
        {
          "level": 3,
          "title": "12.1.2 优化渲染性能",
          "slug": "_12-1-2-优化渲染性能"
        },
        {
          "level": 2,
          "title": "12.2 内部代码质量",
          "slug": "_12-2-内部代码质量"
        },
        {
          "level": 3,
          "title": "12.2.1 理解CSS",
          "slug": "_12-2-1-理解css"
        },
        {
          "level": 3,
          "title": "12.2.2 代码质量的例子",
          "slug": "_12-2-2-代码质量的例子"
        },
        {
          "level": 3,
          "title": "12.2.3 管理层叠",
          "slug": "_12-2-3-管理层叠"
        },
        {
          "level": 3,
          "title": "12.2.4 结构命名与CSS方法论",
          "slug": "_12-2-4-结构命名与css方法论"
        }
      ]
    },
    {
      "title": "第9章 表单与数据表",
      "frontmatter": {},
      "regularPath": "/read/css-mastery/9.%E8%A1%A8%E5%8D%95%E4%B8%8E%E6%95%B0%E6%8D%AE%E8%A1%A8.html",
      "relativePath": "read/css-mastery/9.表单与数据表.md",
      "key": "v-3c9b42b3",
      "path": "/read/css-mastery/9.%E8%A1%A8%E5%8D%95%E4%B8%8E%E6%95%B0%E6%8D%AE%E8%A1%A8.html",
      "headers": [
        {
          "level": 2,
          "title": "9.1 设计数据表",
          "slug": "_9-1-设计数据表"
        },
        {
          "level": 3,
          "title": "9.1.1 表格专有元素",
          "slug": "_9-1-1-表格专有元素"
        },
        {
          "level": 3,
          "title": "9.1.2 为表格应用样式",
          "slug": "_9-1-2-为表格应用样式"
        },
        {
          "level": 3,
          "title": "9.1.3 响应式表格",
          "slug": "_9-1-3-响应式表格"
        },
        {
          "level": 2,
          "title": "9.2 表单",
          "slug": "_9-2-表单"
        },
        {
          "level": 3,
          "title": "9.2.1 简单的表单",
          "slug": "_9-2-1-简单的表单"
        },
        {
          "level": 3,
          "title": "9.2.2 表单反馈与帮助",
          "slug": "_9-2-2-表单反馈与帮助"
        },
        {
          "level": 3,
          "title": "9.2.3 高级表单样式",
          "slug": "_9-2-3-高级表单样式"
        }
      ]
    },
    {
      "title": "精通 CSS",
      "frontmatter": {},
      "regularPath": "/read/css-mastery/",
      "relativePath": "read/css-mastery/README.md",
      "key": "v-f0f58de6",
      "path": "/read/css-mastery/",
      "headers": [
        {
          "level": 2,
          "title": "内容提要：",
          "slug": "内容提要"
        },
        {
          "level": 3,
          "title": "第8章 响应式 →",
          "slug": "第8章-响应式-→"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/read/professional-javascript/",
      "relativePath": "read/professional-javascript/README.md",
      "key": "v-66a8bdcd",
      "path": "/read/professional-javascript/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "读书笔记",
        "items": [
          {
            "text": "精通CSS",
            "link": "/read/css-mastery/"
          },
          {
            "text": "Javascript程序编程",
            "link": "/read/professional-javascript/"
          }
        ]
      },
      {
        "text": "学习笔记",
        "link": "/learn"
      },
      {
        "text": "我的博客",
        "link": "https://www.cnblogs.com/ccti7/"
      }
    ],
    "sidebar": {
      "/read/css-mastery/": [
        "8.响应式",
        "9.表单与数据表",
        "10.变换、过渡与动画",
        "11.高级特效",
        "12.品控与流程"
      ]
    }
  }
}